defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "main"
      pdf: true

url: "https://odinuv.com"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .git/
  - .gitignore
  - .dockerignore
  - .idea/
  - README.md
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - provisioning/


sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
