name: GitHub Actions
on: [ push ]
concurrency: ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker-compose run --rm -e JEKYLL_ENV=production site bundle exec jekyll build

      - name: Publish
        if: ${{ $GITHUB_REF_NAME == 'main' }}
        run: |
          printf $FTP_TARGET
          printf "${{ vars.FTP_USER }}"
          docker-compose run --rm -e FTP_PASS -e FTP_TARGET -e FTP_USER site /code/provisioning/deploy.sh partial
        env:
          FTP_USER: ${{ vars.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_TARGET: ${{ vars.FTP_TARGET }}
